output-dir = "tests/logs"
log-level = "TRACE:DEBUG"
python-path = [
    "/workspaces/robotframework-openapitools/tests/generated",
    "/workspaces/robotframework-openapitools/tests/user_implemented",
]

[variables]
ROOT = "/workspaces/robotframework-openapitools"
