# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Continuous integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#   schedule:
#     - cron: '15 10 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest']
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install
    - name: Check types on Linux with latest Python 3.13
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.13'
      run: |
        inv type-check
    - name: Run linting on Linux with Python 3.13
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.13'
      run: |
        inv lint
    - name: Create distribution
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10'
      run: |
        inv build
    - uses: actions/upload-artifact@v4
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10'
      with:
        name: openapitools-wheel
        path: dist/robotframework_openapitools-*-py3-none-any.whl

  testing:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest']
        python-version: ['3.10', '3.11', '3.12', '3.13']
        robot-version: ['6.1.1', '7.0.0']
        exclude:
          - os: 'windows-latest'
            python-version: '3.10'
          - os: 'windows-latest'
            python-version: '3.11'
          - os: 'windows-latest'
            python-version: '3.12'
          - os: 'ubuntu-latest'
            python-version: '3.10'
            robot-version: '6.1.1'
          - os: 'ubuntu-latest'
            python-version: '3.11'
            robot-version: '6.1.1'
          - os: 'ubuntu-latest'
            python-version: '3.12'
            robot-version: '6.1.1'
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install
        pip install robotframework==${{ matrix.robot-version}}
    - name: Start the test server in the background
      run: |
        inv start-api &
    - name: Run tests
      run: |
       inv tests
    - uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: Test results-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.robot-version}}
        path: zip_results/output
